[tool.poetry]
name = "jwrite"
version = "0.1.0"
description = "Notepad clone made with PySide6"
authors = ["jrrom"]
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.12,>=3.7"
pyside6 = "^6.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
